// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBchPiBCTBYW5F633DvaIxvpNUiFG3ps1w',
    appId: '1:740379920254:web:f159126b8aa1a30a06552f',
    messagingSenderId: '740379920254',
    projectId: 'bad-pixel-art-prod',
    authDomain: 'bad-pixel-art-prod.firebaseapp.com',
    storageBucket: 'bad-pixel-art-prod.firebasestorage.app',
    measurementId: 'G-QYJWZTG2CQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANvxKQk3mjsfopILEgEHyr3NoijraAb5c',
    appId: '1:740379920254:android:e442ab1e6b4d450906552f',
    messagingSenderId: '740379920254',
    projectId: 'bad-pixel-art-prod',
    storageBucket: 'bad-pixel-art-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaiXZhJKkhsNiIG-JiyEuN5cY4f6HpMeY',
    appId: '1:740379920254:ios:cf64527b8ed162ba06552f',
    messagingSenderId: '740379920254',
    projectId: 'bad-pixel-art-prod',
    storageBucket: 'bad-pixel-art-prod.firebasestorage.app',
    iosBundleId: 'com.mweastwood.badPixelArt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaiXZhJKkhsNiIG-JiyEuN5cY4f6HpMeY',
    appId: '1:740379920254:ios:cf64527b8ed162ba06552f',
    messagingSenderId: '740379920254',
    projectId: 'bad-pixel-art-prod',
    storageBucket: 'bad-pixel-art-prod.firebasestorage.app',
    iosBundleId: 'com.mweastwood.badPixelArt',
  );
}
