// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5NYeoG5gEU44uU1QczWo9W8hTxXX5Wa8',
    appId: '1:402346842627:web:8bcb2b67ef50d85eae8c36',
    messagingSenderId: '402346842627',
    projectId: 'bad-pixel-art-dev',
    authDomain: 'bad-pixel-art-dev.firebaseapp.com',
    storageBucket: 'bad-pixel-art-dev.firebasestorage.app',
    measurementId: 'G-XYSS673G9P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqUErD7EV6HwY8CvlXawrPdGB2hXqrxFI',
    appId: '1:402346842627:android:d409cb5be6382660ae8c36',
    messagingSenderId: '402346842627',
    projectId: 'bad-pixel-art-dev',
    storageBucket: 'bad-pixel-art-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeal_C6tx2IMiOlGi0noSFSlI9vqlWj_I',
    appId: '1:402346842627:ios:01d48d85da0941acae8c36',
    messagingSenderId: '402346842627',
    projectId: 'bad-pixel-art-dev',
    storageBucket: 'bad-pixel-art-dev.firebasestorage.app',
    iosBundleId: 'com.mweastwood.badPixelArt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeal_C6tx2IMiOlGi0noSFSlI9vqlWj_I',
    appId: '1:402346842627:ios:01d48d85da0941acae8c36',
    messagingSenderId: '402346842627',
    projectId: 'bad-pixel-art-dev',
    storageBucket: 'bad-pixel-art-dev.firebasestorage.app',
    iosBundleId: 'com.mweastwood.badPixelArt',
  );
}
